//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFeCTe
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.EMPRESA = new HashSet<EMPRESA>();
        }
    
        public int USUARIO_ID { get; set; }
        public string LOGIN { get; set; }
        public string SENHA { get; set; }
        public string PERFIL { get; set; }
        public Nullable<int> CT_COMP_ENCERRAMENTO { get; set; }
        public string LOCAL_ACESSO { get; set; }
    
        public virtual ICollection<EMPRESA> EMPRESA { get; set; }
    }
}
